myInt1=5
myInt2=int(5)
print(myInt1)
print(type(myInt1))
print(myInt2)
print(type(myInt2))
myFloat1=5.0
myFloat2=float(5.0)
print(myFloat1)
print(type(myFloat1))
print(myFloat2)
print(type(myFloat2))
myComplex1=5+2j
myComplex2=2j
myComplex3=complex(5,2)
print(myComplex1)
print(type(myComplex1))
print(myComplex2)
print(type(myComplex2))
print(myComplex3)
print(type(myComplex3))
myBool1=True
myBool2=False
print(myBool1)
print(type(myBool1))
print(myBool2)
print(type(myBool2))
myBool3=bool(0)
print(myBool3)
print(type(myBool3))
myBool4=bool("Malia Chopra")
print(myBool4)
print(type(myBool4))
mystr1="Hello"
mystr2=str("Hello")
print(mystr1,type(mystr1),mystr2,type(mystr2))
print(True==1)
print(True is 1)
print(True is not 1)